language: node_js
node_js:
  - '4.1'
  - 0.10.32
  - node
  - iojs
script:
  - npm run build
  - npm test
sudo: false
deploy:
  provider: npm
  email: development@esendex.com
  api_key:
    secure: MtG41m/g0a8xLoHpmxgHEc2hQGAIOTheFwCzPCJu3RREP60VEbAi9JOYL45fMdcMClfK6fZsN+kH0b88rXOBFr5bseeNr4Sm4Nr1soozizOQKntv36Y4psduF+o9+jPsOqdCX+tzbpsreqMtkgBlY1DmlNapBVo5DtXP/RMD/YUc+7yMoHWs+nTXW93qG8i7b1w+ukmndYD2qJbr+72+hw0gxM511jK9/H32wwdWT5Yr5w30GmWj7Ocl+aQ5ckINZqwiGpmejJ6bI4adlTDQcPJhP2B1Q18Vg0XiygE5mUeelfP7kjpgdxzgIUJVwxai8h6pvSMl5XzFyqYx792UHmCaYl1W1Xk1NFFw8Ofl7MiZ4ioiZFYJxpM2sV+V+FRAMiYosIXNntjhzMC6LARewzWur4D/kWhXU+nrdb0n+dQb5czfuemZL3zmdFyGIbiahBT1iaAJTBl2oYY2zTEvDEl3lJMo/80hv+pSXbRNxbO51/er2hxhMc+Arn3Q1/eNOl/K4rw1+ggai2bVDeJyPWUKMRGswP2fZKI6WxE6EKn7KvdsudQqCRz9GNS/TQzxM7jEVaAdtTMQkPsIPgJdNL4uDniFbhxV3/0BjrGl1BOfE26wtzKB4kDnAPd3hSNbtTZcIcynN0SQuhLhvZWdxrZyAv28DOEslP1mO6msnfQ=
  on:
    tags: true
    repo: esendex/esendex-node-sdk
    node: node
  skip_cleanup: true
notifications:
  email: false