language: node_js
node_js:
  - '4.1'
  - '0.10.32'
  - 'node'
  - 'iojs'
before_script:
  - ./node_modules/.bin/tsd install
script:
  - npm run build
  - npm test
after_script:
  - npm run coveralls
sudo: false